"""
main.py
FastAPI server for CivicBridge AI.
Exposes endpoints for complaint submission and health checks.
Also serves the frontend as static files at /app
"""

import os
import logging
from pathlib import Path
from typing import Optional, Dict

from fastapi import FastAPI, File, Form, UploadFile, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.gzip import GZipMiddleware
from fastapi.responses import JSONResponse, RedirectResponse
from fastapi.staticfiles import StaticFiles
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.util import get_remote_address
from slowapi.errors import RateLimitExceeded

try:
    from backend.gemini_bridge import analyze_civic_complaint
    from backend.gcs_helper import upload_image_to_gcs
except ImportError:
    from gemini_bridge import analyze_civic_complaint
    from gcs_helper import upload_image_to_gcs

# ──────────────────────────────────────────────
# Setup Logging
# ──────────────────────────────────────────────
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")
logger = logging.getLogger("CivicBridge.API")

# ──────────────────────────────────────────────
# App Setup & Security
# ──────────────────────────────────────────────
limiter = Limiter(key_func=get_remote_address)
app = FastAPI(
    title="CivicBridge AI",
    description="Converts messy citizen complaints into structured government dispatch tickets using Gemini AI.",
    version="1.0.0",
)
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

# Efficiency: Compress responses
app.add_middleware(GZipMiddleware, minimum_size=500)

# Security: Strict CORS (No longer wildcard '*')
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:8000", "http://127.0.0.1:8000", "https://civicbridge-ai.run.app"],
    allow_credentials=True,
    allow_methods=["GET", "POST", "OPTIONS"],
    allow_headers=["*"],
)

# Security: Custom HTTP Headers Middleware
@app.middleware("http")
async def add_security_headers(request: Request, call_next):
    response = await call_next(request)
    response.headers["X-Content-Type-Options"] = "nosniff"
    response.headers["X-Frame-Options"] = "DENY"
    response.headers["Strict-Transport-Security"] = "max-age=31536000; includeSubDomains"
    return response

# Serve the frontend as static files at /app
_FRONTEND_DIR = Path(__file__).parent.parent / "frontend"
if _FRONTEND_DIR.exists():
    app.mount("/app", StaticFiles(directory=str(_FRONTEND_DIR), html=True), name="frontend")

ALLOWED_IMAGE_TYPES = {"image/jpeg", "image/jpg", "image/png", "image/webp", "image/gif"}


# ──────────────────────────────────────────────
# Endpoints
# ──────────────────────────────────────────────

@app.get("/", include_in_schema=False)
def root_redirect() -> RedirectResponse:
    """Redirect root to the frontend app."""
    return RedirectResponse(url="/app")


@app.get("/api/health", tags=["System"])
def health_check() -> Dict[str, str]:
    """Quick health check to verify the server is running."""
    return {"status": "ok", "service": "CivicBridge AI", "version": "1.0.0"}


@app.post("/api/submit-complaint", tags=["Complaints"])
@limiter.limit("10/minute")
async def submit_complaint(
    request: Request,
    description: str = Form(..., description="Citizen's complaint in any language or style"),
    location: Optional[str] = Form(default=None, description="Optional location hint"),
    image: Optional[UploadFile] = File(default=None, description="Optional photo of the issue"),
) -> JSONResponse:
    """
    Main endpoint: Accepts a civic complaint (text + optional image) and returns
    a structured Dispatch Ticket generated by Gemini 1.5 Flash.
    """
    # Validate description
    if not description or len(description.strip()) < 5:
        raise HTTPException(status_code=400, detail="Complaint description is too short. Please provide more detail.")

    # Read image bytes if provided
    image_bytes = None
    image_mime = "image/jpeg"
    if image and image.filename:
        mime_type = image.content_type or "image/jpeg"
        if mime_type not in ALLOWED_IMAGE_TYPES:
            raise HTTPException(
                status_code=415,
                detail=f"Unsupported image type '{mime_type}'. Use JPEG, PNG, WEBP, or GIF."
            )
        image_bytes = await image.read()
        image_mime = mime_type
        if len(image_bytes) > 10 * 1024 * 1024:  # 10 MB cap
            raise HTTPException(status_code=413, detail="Image too large. Max 10 MB.")

    try:
        gcs_url = None
        if image_bytes:
            # Google Services: Upload to Cloud Storage
            gcs_url = upload_image_to_gcs(image_bytes, image_mime)
            logger.info(f"Processing complaint via Gemini. GCS URL: {gcs_url}")
        else:
            logger.info("Processing complaint via Gemini. No image attached.")

        result = analyze_civic_complaint(
            description=description.strip(),
            location=location.strip() if location else None,
            image_bytes=image_bytes,
            image_mime_type=image_mime,
            gcs_url=gcs_url
        )
        return JSONResponse(content=result, status_code=200)

    except Exception as e:
        logger.error(f"Gemini analysis failed: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Gemini analysis failed: {str(e)}"
        )


import functools
@app.get("/api/departments", tags=["Reference"])
@functools.lru_cache(maxsize=1)
def get_departments() -> Dict[str, list]:
    """Returns the list of routable city departments."""
    return {
        "departments": [
            {"id": "DOT", "name": "Department of Transportation", "issues": ["Pothole", "Road Damage", "Traffic Signal"]},
            {"id": "WPA", "name": "Water & Power Authority", "issues": ["Water Leak", "Sewage", "Flooding"]},
            {"id": "ELE", "name": "Electrical & Power Department", "issues": ["Broken Streetlight", "Downed Wires", "Power Outage"]},
            {"id": "WMD", "name": "Waste Management Division", "issues": ["Illegal Dumping", "Overflowing Bin", "Litter"]},
            {"id": "PNR", "name": "Parks & Recreation Department", "issues": ["Fallen Tree", "Damaged Park Equipment", "Overgrown Vegetation"]},
            {"id": "PWB", "name": "Public Works — Beautification Unit", "issues": ["Graffiti", "Vandalism"]},
            {"id": "EMG", "name": "Emergency Services", "issues": ["Gas Leak", "Structural Collapse", "Fire Hazard"]},
        ]
    }
