"""
main.py
FastAPI server for CivicBridge AI.
Exposes endpoints for complaint submission and health checks.
Also serves the frontend as static files at /app
"""

import os
import traceback
from pathlib import Path
from typing import Optional

from fastapi import FastAPI, File, Form, UploadFile, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, RedirectResponse
from fastapi.staticfiles import StaticFiles

from gemini_bridge import analyze_civic_complaint

# ──────────────────────────────────────────────
# App Setup
# ──────────────────────────────────────────────
app = FastAPI(
    title="CivicBridge AI",
    description="Converts messy citizen complaints into structured government dispatch tickets using Gemini AI.",
    version="1.0.0",
)

# Allow requests from local file:// and localhost frontends
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Serve the frontend as static files at /app
_FRONTEND_DIR = Path(__file__).parent.parent / "frontend"
if _FRONTEND_DIR.exists():
    app.mount("/app", StaticFiles(directory=str(_FRONTEND_DIR), html=True), name="frontend")

ALLOWED_IMAGE_TYPES = {"image/jpeg", "image/jpg", "image/png", "image/webp", "image/gif"}


# ──────────────────────────────────────────────
# Endpoints
# ──────────────────────────────────────────────

@app.get("/", include_in_schema=False)
def root_redirect():
    """Redirect root to the frontend app."""
    return RedirectResponse(url="/app")


@app.get("/api/health", tags=["System"])
def health_check():
    """Quick health check to verify the server is running."""
    return {"status": "ok", "service": "CivicBridge AI", "version": "1.0.0"}


@app.post("/api/submit-complaint", tags=["Complaints"])
async def submit_complaint(
    description: str = Form(..., description="Citizen's complaint in any language or style"),
    location: Optional[str] = Form(default=None, description="Optional location hint"),
    image: Optional[UploadFile] = File(default=None, description="Optional photo of the issue"),
):
    """
    Main endpoint: Accepts a civic complaint (text + optional image) and returns
    a structured Dispatch Ticket generated by Gemini 1.5 Flash.
    """
    # Validate description
    if not description or len(description.strip()) < 5:
        raise HTTPException(status_code=400, detail="Complaint description is too short. Please provide more detail.")

    # Read image bytes if provided
    image_bytes = None
    image_mime = "image/jpeg"
    if image and image.filename:
        mime_type = image.content_type or "image/jpeg"
        if mime_type not in ALLOWED_IMAGE_TYPES:
            raise HTTPException(
                status_code=415,
                detail=f"Unsupported image type '{mime_type}'. Use JPEG, PNG, WEBP, or GIF."
            )
        image_bytes = await image.read()
        image_mime = mime_type
        if len(image_bytes) > 10 * 1024 * 1024:  # 10 MB cap
            raise HTTPException(status_code=413, detail="Image too large. Max 10 MB.")

    try:
        result = analyze_civic_complaint(
            description=description.strip(),
            location=location.strip() if location else None,
            image_bytes=image_bytes,
            image_mime_type=image_mime,
        )
        return JSONResponse(content=result, status_code=200)

    except Exception as e:
        traceback.print_exc()
        raise HTTPException(
            status_code=500,
            detail=f"Gemini analysis failed: {str(e)}"
        )


@app.get("/api/departments", tags=["Reference"])
def get_departments():
    """Returns the list of routable city departments."""
    return {
        "departments": [
            {"id": "DOT", "name": "Department of Transportation", "issues": ["Pothole", "Road Damage", "Traffic Signal"]},
            {"id": "WPA", "name": "Water & Power Authority", "issues": ["Water Leak", "Sewage", "Flooding"]},
            {"id": "ELE", "name": "Electrical & Power Department", "issues": ["Broken Streetlight", "Downed Wires", "Power Outage"]},
            {"id": "WMD", "name": "Waste Management Division", "issues": ["Illegal Dumping", "Overflowing Bin", "Litter"]},
            {"id": "PNR", "name": "Parks & Recreation Department", "issues": ["Fallen Tree", "Damaged Park Equipment", "Overgrown Vegetation"]},
            {"id": "PWB", "name": "Public Works — Beautification Unit", "issues": ["Graffiti", "Vandalism"]},
            {"id": "EMG", "name": "Emergency Services", "issues": ["Gas Leak", "Structural Collapse", "Fire Hazard"]},
        ]
    }
